// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squares.Infrastructure.Persistance;

#nullable disable

namespace Squares.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Squares.Domain.Entities.PointsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ShouldUpdateSquares")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PointsLists");
                });

            modelBuilder.Entity("Squares.Domain.Entities.PointsList", b =>
                {
                    b.OwnsMany("Squares.Domain.Entities.Point", "Points", b1 =>
                        {
                            b1.Property<int>("PointsListId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.HasKey("PointsListId", "Id");

                            b1.ToTable("PointsLists_Points");

                            b1.WithOwner()
                                .HasForeignKey("PointsListId");
                        });

                    b.OwnsMany("Squares.Domain.Entities.Square", "Squares", b1 =>
                        {
                            b1.Property<int>("PointsListId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.HasKey("PointsListId", "Id");

                            b1.ToTable("Square");

                            b1.WithOwner()
                                .HasForeignKey("PointsListId");

                            b1.OwnsMany("Squares.Domain.Entities.Point", "Points", b2 =>
                                {
                                    b2.Property<int>("SquarePointsListId")
                                        .HasColumnType("int");

                                    b2.Property<int>("SquareId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<double>("X")
                                        .HasColumnType("float");

                                    b2.Property<double>("Y")
                                        .HasColumnType("float");

                                    b2.HasKey("SquarePointsListId", "SquareId", "Id");

                                    b2.ToTable("Square_Points");

                                    b2.WithOwner()
                                        .HasForeignKey("SquarePointsListId", "SquareId");
                                });

                            b1.Navigation("Points");
                        });

                    b.Navigation("Points");

                    b.Navigation("Squares");
                });
#pragma warning restore 612, 618
        }
    }
}
